name: Generate snake animation  # 🐍 Generates a snake animation for GitHub contributions

on:
  schedule:  # ⏰ Executes the workflow on a scheduled basis
    - cron: "* */12 * * *"  # 🕐 Executes every 12 hours
  workflow_dispatch:  # 🔄 Allows manual triggering of the workflow
  push:  # 📤 Triggered on a push event
    branches:
      - master  # 🌿 The branch to trigger the action on

jobs:
  generate:
    permissions:
      contents: write  # ✍️ Grants write permissions for the repository contents
    runs-on: ubuntu-latest  # 💻 Runs the workflow on the latest Ubuntu runner
    timeout-minutes: 5  # ⏳ Timeout after 5 minutes if the job takes too long

    steps:
      - name: generate snake.svg  # 🖼 Generates the snake animation as an SVG file
        uses: Platane/snk/svg-only@v3  # 🐍 Uses the Platane/snk action to generate the SVG file
        with:
          github_user_name: ${{ github.repository_owner }}  # 🔑 Uses the repository owner's GitHub username
          outputs: dist/snake.svg?palette=github-dark  # 🎨 Generates the SVG with a GitHub dark theme palette

      - name: push snake.svg to the output branch  # 📤 Pushes the generated SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0  # 🌐 Deploys the SVG to GitHub Pages
        with:
          target_branch: output  # 🔄 Specifies the target branch for output
          build_dir: dist  # 📂 Directory containing the generated files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 🔑 Uses the GitHub token for authentication
